# Dockerfile.dev
FROM golang:1.25-alpine

WORKDIR /app

# Instala ferramentas básicas e o Air (Hot Reload)
RUN apk add --no-cache git
RUN go install github.com/air-verse/air@latest

# Copia arquivos de dependência
COPY go.mod go.sum ./
RUN go mod download

# Copia o código fonte
COPY . .

# Em vez de compilar um binário final, rodamos o Air
# O Air vai rodar seu main.go e reiniciar se detectar mudanças
CMD ["air", "-c", ".air.toml"]