# Chave do projeto no SonarCloud (você pega no painel deles)
sonar.projectKey=soat-hackaton_hack-auth
sonar.organization=soat-hackaton

# Nome de exibição
sonar.projectName=Auth Service
sonar.projectVersion=1.0

# Onde está o código e onde estão os testes
sonar.sources=internal,cmd
sonar.tests=internal
sonar.exclusions=**/*_test.go,**/mocks/**
sonar.test.inclusions=**/*_test.go

# Linguagem
sonar.language=go

# Onde o seu script de teste vai salvar o resultado da cobertura
sonar.go.coverage.reportPaths=coverage.out