apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Herda tudo da base
resources:
  - ../../base

# Aplica o patch de réplicas
patches:
  - path: patch-replicas.yml

# Define o namespace específico de dev (sobrescreve o base)
namespace: hack-auth